# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 08:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom_of_problem', models.TextField()),
                ('action_plan', models.TextField()),
                ('estimation_duration', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerImpact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_of_customer_impact', models.CharField(max_length=30)),
                ('network_interrupt', models.TextField()),
                ('service_interrupt', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DeviceReplacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_device_id', models.CharField(max_length=30)),
                ('old_device_type', models.CharField(max_length=30)),
                ('old_serial_number', models.CharField(max_length=30)),
                ('old_barcode', models.CharField(max_length=30)),
                ('new_device_id', models.CharField(max_length=30)),
                ('new_device_type', models.CharField(max_length=30)),
                ('new_serial_number', models.CharField(max_length=30)),
                ('new_barcode', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='LocationAndDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiberhood', models.CharField(max_length=30)),
                ('site', models.CharField(max_length=30)),
                ('cluster', models.CharField(max_length=30)),
                ('floor_slash_block', models.CharField(max_length=30)),
                ('device_id', models.CharField(max_length=30)),
                ('device_port', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleAndPIC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('pic', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Maintenance')),
            ],
        ),
        migrations.AddField(
            model_name='locationanddevice',
            name='maintenance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Maintenance'),
        ),
        migrations.AddField(
            model_name='devicereplacement',
            name='maintenance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Maintenance'),
        ),
        migrations.AddField(
            model_name='customerimpact',
            name='maintenance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Maintenance'),
        ),
        migrations.AddField(
            model_name='activity',
            name='maintenance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Maintenance'),
        ),
    ]
