# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='document',
            field=models.FileField(default='', upload_to='documents/'),
            preserve_default=False,
        ),
    ]
