# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_activity_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='document',
            field=models.FileField(upload_to=b''),
        ),
    ]
