# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20161018_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='document',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
