# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_auto_20161018_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
